[package]
name = "blightmud"
version = "0.1.0"
authors = ["Linus Probert"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libtelnet-rs = { git = "https://github.com/envis10n/libtelnet-rs" }
termion = "1.5.5"
log = "0.4.8"
simple-logging = "2.0.2"
chrono = "0.4.11"
signal-hook = "0.1.13"
rlua = "0.17.0"
regex = "1.3.7"
dirs = "2.0.2"
strip-ansi-escapes = "0.1.0"
