[package]
name = "blightmud"
version = "0.2.0"
authors = ["Linus Probert"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libtelnet-rs = { git="https://github.com/liquidityc/libtelnet-rs", branch="add_eor_cmd" }
termion = "1.5.5"
log = "0.4.8"
simple-logging = "2.0.2"
chrono = "0.4.11"
signal-hook = "0.1.13"
rlua = "0.17.0"
regex = "1.3.7"
dirs = "2.0.2"
strip-ansi-escapes = "0.1.0"
timer = "0.2.0"
flate2 = "1.0.14"
mdcat = { version = "0.16.1", default-features = false }
pulldown-cmark = "0.7.1"
syntect = "4.1.1"
serde = { version = "1.0", features = ['derive'] }
ron = "0.5"
anyhow = "1.0.31"
lazy_static = "1.4.0"
rs-complete = "0.1.1"
simple-error = "0.2.1"
getopts = "0.2.21"
