name: Rust

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: ["*"]

jobs:
  test_macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/git
          ~/.cargo/registry
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Setup toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy, rustfmt
        override: true
    - name: Formatting
      run: cargo fmt -- --check
    - name: Check
      run: cargo check --locked
    - name: Clippy
      run: cargo clippy --locked
    - name: Test
      run: cargo test --locked
    - name: Build
      run: cargo build --release

  test_ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/git
          ~/.cargo/registry
          ~/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Formatting
      run: cargo fmt -- --check
    - name: Check
      run: cargo check --locked
    - name: Clippy
      run: cargo clippy --locked
    - name: Test
      run: cargo test --locked
    - name: Build
      run: cargo build --release
